import {
  NewsDatatype,
  TradeDataType,
  CompanyData as CompanyDataType,
  MarketDataType,
} from '@/app/types';

export const MarketData: MarketDataType[] = [
  {
    company: 'SpaceX',
    type: 'OFFER',
    price: 194.5,
    priceVsMarket: '-22%',
    priceVsLast: '5%',
    size: '$7.8M',
    structure: 'SPV (1/20)',
    shareClass: 'Unknown',
    source: 'Top Broker',
    updated: 'Today',
    submitted: '1/21/2025',
  },
  {
    company: 'Stripe',
    type: 'BID',
    price: 65,
    priceVsMarket: '-15%',
    priceVsLast: '-25%',
    size: '$2.5M',
    structure: 'Direct',
    shareClass: 'Common',
    source: 'Verified Seller',
    updated: 'Yesterday',
    submitted: '1/20/2025',
  },
  {
    company: 'Databricks',
    type: 'OFFER',
    price: 110.75,
    priceVsMarket: '8%',
    priceVsLast: '12%',
    size: '$5.0M',
    structure: 'Direct',
    shareClass: 'Preferred',
    source: 'Platform',
    updated: '2 days ago',
    submitted: '1/19/2025',
  },
  {
    company: 'Plaid',
    type: 'BID',
    price: 45.25,
    priceVsMarket: '-5%',
    priceVsLast: '-10%',
    size: '$1.2M',
    structure: 'SPV (1/10)',
    shareClass: 'Common',
    source: 'Top Broker',
    updated: '3 days ago',
    submitted: '1/18/2025',
  },
  {
    company: 'Anthropic',
    type: 'OFFER',
    price: 85,
    priceVsMarket: '15%',
    priceVsLast: '20%',
    size: '$3.5M',
    structure: 'Direct',
    shareClass: 'Preferred',
    source: 'Verified Seller',
    updated: '4 days ago',
    submitted: '1/17/2025',
  },
  {
    company: 'Notion',
    type: 'OFFER',
    price: 55.25,
    priceVsMarket: '12%',
    priceVsLast: '-8%',
    size: '$4.2M',
    structure: 'Direct',
    shareClass: 'Common',
    source: 'Verified Seller',
    updated: 'Today',
    submitted: '1/22/2025',
  },
  {
    company: 'Rippletrade',
    type: 'BID',
    price: 92.75,
    priceVsMarket: '-3%',
    priceVsLast: '15%',
    size: '$2.8M',
    structure: 'SPV (1/15)',
    shareClass: 'Preferred',
    source: 'Top Broker',
    updated: '2 days ago',
    submitted: '1/20/2025',
  },
  {
    company: 'Sealand',
    type: 'OFFER',
    price: 145.5,
    priceVsMarket: '8%',
    priceVsLast: '-12%',
    size: '$5.5M',
    structure: 'Direct',
    shareClass: 'Common',
    source: 'Platform',
    updated: 'Today',
    submitted: '1/22/2025',
  },
  {
    company: 'Vercel',
    type: 'BID',
    price: 78.25,
    priceVsMarket: '-5%',
    priceVsLast: '10%',
    size: '$3.1M',
    structure: 'Direct',
    shareClass: 'Preferred',
    source: 'Verified Seller',
    updated: 'Yesterday',
    submitted: '1/21/2025',
  },
];

export const TradeData: TradeDataType[] = [
  {
    company: 'Kraken',
    type: 'CLOSED TRADE',
    closedDate: 'January 21, 2025',
    uploadDate: 'January 21, 2025',
    pricePerShare: 18.5,
    estValuation: '$3.7B val. (est.)',
    priceVsLastRound: '-97%',
    priceVsMarketPrice: '-2%',
    volume: '$3.2M',
    structure: 'Direct',
    shareClass: 'Common',
  },
  {
    company: 'Dataminr',
    type: 'CLOSED TRADE',
    closedDate: 'January 16, 2025',
    uploadDate: 'January 17, 2025',
    pricePerShare: 14,
    estValuation: '$1.3B val. (est.)',
    priceVsLastRound: '+6%',
    priceVsMarketPrice: null,
    volume: '$700.0K',
    structure: 'Direct',
    shareClass: 'Common',
  },
  {
    company: 'SambaNova Systems',
    type: 'CLOSED TRADE',
    closedDate: 'January 13, 2025',
    uploadDate: 'January 14, 2025',
    pricePerShare: 29,
    estValuation: '$1.5B val. (est.)',
    priceVsLastRound: '-17%',
    priceVsMarketPrice: null,
    volume: '$800.0K',
    structure: 'Direct',
    shareClass: 'Common',
  },
  {
    company: 'Redwood Materials',
    type: 'CLOSED TRADE',
    closedDate: 'January 10, 2025',
    uploadDate: 'January 14, 2025',
    pricePerShare: 52,
    estValuation: '$5.4B val. (est.)',
    priceVsLastRound: '+9%',
    priceVsMarketPrice: '+3%',
    volume: '$2.5M',
    structure: 'Direct',
    shareClass: 'Preferred',
  },
  {
    company: 'Cohere',
    type: 'CLOSED TRADE',
    closedDate: 'January 8, 2025',
    uploadDate: 'January 8, 2025',
    pricePerShare: 153.77,
    estValuation: '$4.0B val. (est.)',
    priceVsLastRound: '-27%',
    priceVsMarketPrice: '-8%',
    volume: '$840.0K',
    structure: 'Direct',
    shareClass: 'Common',
  },
  {
    company: 'Kin',
    type: 'CLOSED TRADE',
    closedDate: 'January 6, 2025',
    uploadDate: 'January 14, 2025',
    pricePerShare: 38,
    estValuation: '$632.0M val. (est.)',
    priceVsLastRound: '-37%',
    priceVsMarketPrice: null,
    volume: '$235.0K',
    structure: 'Direct',
    shareClass: 'Common',
  },
  {
    company: 'xAI',
    type: 'CLOSED TRADE',
    closedDate: 'January 3, 2025',
    uploadDate: 'January 14, 2025',
    pricePerShare: 23.82,
    estValuation: '$55.0B val. (est.)',
    priceVsLastRound: '+10%',
    priceVsMarketPrice: '-38%',
    volume: '$750.0K',
    structure: 'SPV (0/15) (☆)',
    shareClass: 'Preferred',
  },
  {
    company: 'Grog',
    type: 'CLOSED TRADE',
    closedDate: 'December 31, 2024',
    uploadDate: 'January 6, 2025',
    pricePerShare: 16.4,
    estValuation: '$2.9B val. (est.)',
    priceVsLastRound: '+2%',
    priceVsMarketPrice: '+0%',
    volume: '$16.0M',
    structure: 'SPV (0/0)',
    shareClass: 'Common',
  },
  {
    company: 'CoreWeave',
    type: 'CLOSED TRADE',
    closedDate: 'December 28, 2024',
    uploadDate: 'January 8, 2025',
    pricePerShare: 1050,
    estValuation: '$25.7B val. (est.)',
    priceVsLastRound: '+12%',
    priceVsMarketPrice: '-16%',
    volume: '$430.5K',
    structure: 'Direct',
    shareClass: 'Common',
  },
  {
    company: 'Klarna',
    type: 'CLOSED TRADE',
    closedDate: 'December 25, 2024',
    uploadDate: 'January 7, 2025',
    pricePerShare: 500,
    estValuation: '$15.2B val. (est.)',
    priceVsLastRound: '+5%',
    priceVsMarketPrice: null,
    volume: '$5.0M',
    structure: 'Direct',
    shareClass: 'Common',
  },
  {
    company: 'SpaceX',
    type: 'CLOSED TRADE',
    closedDate: 'December 24, 2024',
    uploadDate: 'December 27, 2024',
    pricePerShare: 128,
    estValuation: '$242.2B val. (est.)',
    priceVsLastRound: '-31%',
    priceVsMarketPrice: '-49%',
    volume: '$100.0K',
    structure: 'SPV (0/0) (☆)',
    shareClass: 'Preferred',
  },
  {
    company: 'Epic Games',
    type: 'CLOSED TRADE',
    closedDate: 'December 23, 2024',
    uploadDate: 'December 24, 2024',
    pricePerShare: 435,
    estValuation: '$16.3B val. (est.)',
    priceVsLastRound: '-28%',
    priceVsMarketPrice: '-1%',
    volume: '$1.5M',
    structure: 'Direct',
    shareClass: 'Common',
  },
];

export const NewsData: NewsDatatype[] = [
  {
    company: 'Stripe',
    headline:
      'Stripe is laying off 300 people, but says it still plans to hire in 2025',
    sector: 'Fintech: Payments',
    date: '23 minutes ago',
    sentiment: 'Negative',
  },
  {
    company: 'Meta',
    headline: "Meta's Ambition to Merge WhatsApp, Instagram, and Facebook",
    sector: 'Social',
    date: '27 minutes ago',
    sentiment: 'Positive',
  },
  {
    company: 'Microsoft',
    headline: 'Microsoft to become latest member of CISPE',
    sector: 'SaaS',
    date: '31 minutes ago',
    sentiment: 'Positive',
  },
  {
    company: 'Apple',
    headline: 'IDs in Apple Wallet will be coming to Illinois',
    sector: 'Electronics',
    date: '33 minutes ago',
    sentiment: 'Positive',
  },
  {
    company: 'Alphabet',
    headline: "Alphabet Stock Has Tesla-Like Catalysts, and it's on the Rise",
    sector: 'Search Engine',
    date: '44 minutes ago',
    sentiment: 'Positive',
  },
  {
    company: 'Visa',
    headline:
      'V Investors Have Opportunity to Lead Visa Inc. Securities Fraud Lawsuit',
    sector: 'Fintech: Payments',
    date: 'an hour ago',
    sentiment: 'Negative',
  },
  {
    company: 'Advarra',
    headline: 'Advarra Introduces Study Collaboration Solution',
    sector: 'Biotech',
    date: 'an hour ago',
    sentiment: 'Positive',
  },
  {
    company: 'Virgin Galactic',
    headline: 'Virgin Galactic Target of Unusually High Options Trading',
    sector: 'Aerospace/Defense',
    date: 'an hour ago',
    sentiment: 'Positive',
  },
  {
    company: 'Flexport',
    headline: 'Flexport alums arm 3PLs with tools to refine shipper outreach',
    sector: 'Logistics',
    date: 'an hour ago',
    sentiment: 'Positive',
  },
  {
    company: 'Uber',
    headline: 'Delta ending partnership with Lyft, starting new one with Uber',
    sector: 'City Mobility',
    date: 'an hour ago',
    sentiment: 'Positive',
  },
];

export const CompanyData: CompanyDataType[] = [
  {
    company: 'Epic Games',
    marketPrice: 445,
    estValuation: 16.7,
    vsLastRound: '↓ -26.00%',
    performance3M: '↑ 1.00%',
    lastPrimaryRound: {
      Amount: '$600',
      volume: '$22.5B',
      date: '2024-09-30',
    },
    lastTrade: {
      Amount: '$445',
      volume: '$16.75B',
      date: '2025-01-11',
    },
    recentTradingHistory: {
      Amount: '$445',
      volume: '$16.75B',
      bid_volume: '$5.2M',
    },
  },
  {
    company: 'Epic Games',
    marketPrice: 445,
    estValuation: 16.7,
    vsLastRound: '↓ -26.00%',
    performance3M: '↑ 1.00%',
    lastPrimaryRound: {
      Amount: '$600',
      volume: '$22.5B',
      date: '2024-09-30',
    },
    lastTrade: {
      Amount: '$445',
      volume: '$16.75B',
      date: '2025-01-11',
    },
    recentTradingHistory: {
      Amount: '$445',
      volume: '$16.75B',
      bid_volume: '$5.2M',
    },
  },
  {
    company: 'Epic Games',
    marketPrice: 445,
    estValuation: 16.7,
    vsLastRound: '↓ -26.00%',
    performance3M: '↑ 1.00%',
    lastPrimaryRound: {
      Amount: '$600',
      volume: '$22.5B',
      date: '2024-09-30',
    },
    lastTrade: {
      Amount: '$445',
      volume: '$16.75B',
      date: '2025-01-11',
    },
    recentTradingHistory: {
      Amount: '$445',
      volume: '$16.75B',
      bid_volume: '$5.2M',
    },
  },
];
